Repository ArkEcosystem/AIPs, pull requests merged in 2019-02, with the labels that each got.

#61 docs: update ark ecosystem role
  AIPS/aip-1.md
Labels: Complexity: Low, Status: Needs Review, Type: Documentation

#66 docs: update aip status in readme
  README.md
Labels: Complexity: Low, Status: Contributor Approved, Status: Needs Review

#67 docs: fix readme AIP number
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Documentation

#71 docs: update the standards track categories
  AIP-template.md
  AIPS/aip-1.md
Labels: Complexity: Low, Type: Documentation
