Repository ArkEcosystem/AIPs, pull requests merged in 2019-08, with the labels that each got.

#118 docs: update AIP-103 to its implementation level
  AIPS/aip-103.md
Labels: Complexity: High, Type: Documentation

#121 fix: remove // from uris
  AIPS/aip-26.md
Labels: Complexity: Low, Type: Bugfix

#119 docs: update AIP29 to reflect changes in 2.6
  AIPS/aip-29.md
Labels: Complexity: High, Type: Documentation

#124 docs: update AIP11, AIP18, AIP102, AIP103
  AIPS/aip-102.md
  AIPS/aip-103.md
  AIPS/aip-11.md
  AIPS/aip-18.md
Labels: Complexity: Medium, Type: Documentation
