Repository ArkEcosystem/AIPs, pull requests merged in 2019-05, with the labels that each got.

#86 Adjust text about transaction expiration
  AIPS/aip-11.md
Labels: Complexity: Low

#88 docs: update AIP11 & AIP18
  AIPS/aip-11.md
  AIPS/aip-18.md
Labels: Complexity: Medium, Type: Documentation

#89 docs: core-vm module - draft for first idea discussion
  AIPS/aip-81.md
Labels: Complexity: High, Type: Documentation

#91 AIP-33: Modular Voting Logic
  AIPS/aip-33.md
Labels: Complexity: Low, Status: In Progress

#92 AIP-34: Modular Consensus Logic
  AIPS/aip-34.md
Labels: Complexity: Low, Status: In Progress

#93 AIP-35: Plugin Package Manager
  AIPS/aip-35.md
Labels: Complexity: Low, Status: In Progress

#96 chore: typos
  AIPS/aip-33.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task
