Repository ArkEcosystem/AIPs, pull requests merged in 2019-10, with the labels that each got.

#131 AIP-126 Ark covenants
  AIPS/aip-126.md
  README.md
Labels: Complexity: Low, Status: Needs Review

#134 docs: aip102 updates (naming and new image)
  AIPS/aip-102.md
  assets/aip-102/scenario-basic.png
Labels: Complexity: Low, Type: Documentation

#135 docs: fix name typo
  AIPS/aip-102.md
Labels: Complexity: Low, Status: Contributor Approved

#138 fix: typo
  AIPS/aip-126.md
Labels: Complexity: Low, Type: Bugfix
